// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agxntsneoraapdbrakwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFneG50c25lb3JhYXBkYnJha3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTM1MTgsImV4cCI6MjA2NTU2OTUxOH0.1ol9s8lQjStihx4fc4yahuQuvh9rKuKp3MYyP_EDTsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);